### ISSUE TITLE
Error: The getter 'accentColor' isn't defined for the class 'ThemeData'. doesn't work from flutter_paystack

### ISSUE THREAD

**Issue by kehindemary** [wilburt/flutter_paystack#162]
../.pub-cache/git/flutter_paystack-a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01/lib/src/widgets/input/pin_field.dart:48:55: Error: The getter 'accentColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('../programs/flutter/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'accentColor'.
                  BorderSide(color: Theme.of(context).accentColor, width: 1.0)),

**Comment by devfolorunso** [comment]
I'm having the same issue, have you been able to solve this @kehindemary

**Comment by psalmskalu** [comment]
This error is popping up everywhere as people upgrade their flutter to latest version. I have had to discontinue using Paystack plugin on three of my apps already. Can you guys fix this already.

Just change ThemeData's deprecated accentColor to secondary

**Comment by hardiklakhalani** [comment]
I'm using this one, hopefully _temporary_
https://github.com/definitelyme/flutter_paystack/pull/1

```yaml
  flutter_paystack:
    git:
      url: https://github.com/definitelyme/flutter_paystack.git
      ref: 3faac4c999314bad4e61860006136926e0bc982e
```
