### ISSUE TITLE
http package issue

### ISSUE THREAD

**Issue by burakhan15** [wilburt/flutter_paystack#178]
Updating the http package to the new version in your library. 0.13.5 to 1.1.0

**Comment by zamargab** [comment]
Yes.. I am facing this issue. please we need a fix ASAP. Thanks so much

**Comment by peterchibunna** [comment]
I have created a pull request that addresses the issues. In the meantime you can install `flutter_paystack` by editing your `pubspec.yaml` like this:

```
  flutter_paystack:
    git:
      url: https://github.com/peterchibunna/flutter_paystack
      ref: master
```
