### ISSUE TITLE
 flutter_paystack ^1.0.7 

### ISSUE THREAD

**Issue by gelocaindoy** [wilburt/flutter_paystack#179]
which depends on intl ^0.17.0, intl ^0.17.0 is required. So, because zcart depends on intl ^0.18.0

**Comment by peterchibunna** [comment]
This Paystack package is preventing me from doing internationalization because of intl version and http version incompatibility issues. I was having similar issues when I was doing react native.

I have created a pull request that addresses the issues. In the meantime you can install `flutter_paystack` by editing your `pubspec.yaml` like this:

```
  flutter_paystack:
    git:
      url: https://github.com/peterchibunna/flutter_paystack
      ref: master
```
