### ISSUE TITLE
Need namespace in android block in app/build.gradle for AGP8 project compatibility

### ISSUE THREAD

**Issue by hardiklakhalani** [wilburt/flutter_paystack#182]
```gradle
android {
    namespace "com.example.xyz"
}
```

**Comment by AnthonyAniobi** [comment]
this version fixes this issue
```
flutter_paystack:
    git:
      url: https://github.com/AnthonyAniobi/flutter_paystack
      ref: master
```
