### ISSUE TITLE
Version bug

### ISSUE THREAD

**Issue by pratikNavapara009** [wilburt/flutter_paystack#186]
And because no versions of flutter_paystack match >1.0.7 <2.0.0, syncfusion_flutter_datepicker >=24.1.47 is incompatible with flutter_paystack ^1.0.7.
So, because laundry depends on both flutter_paystack ^1.0.7 and syncfusion_flutter_datepicker ^24.2.4, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on syncfusion_flutter_datepicker: flutter pub add syncfusion_flutter_datepicker:^21.2.3

**Comment by TheGodOfTheNewWorld** [comment]
If he doesn't merge then do this.

1 - Fork the project.
2 - Upgrade dependences the way you want them to be in, eg `http: ^1.2.1`
3 - Inject the github package straight to your project by following below example 👇

```
 flutter_paystack:
   git:
      url: https://github.com/KarlMathuthu/flutter_paystack.git # Repo link from your profile
      ref: master # branch name
```

> 

I hope this helps 😍
